services:
  coturn:
    image: coturn/coturn:latest
    container_name: voiddrop-coturn
    network_mode: "host"
    environment:
      - TURN_REALM=voiddrop.ru
    command: >
      -n --log-file=stdout --min-port=49152 --max-port=65535
      --external-ip=${EXTERNAL_IP:-your-server-ip} --realm=voiddrop.ru 
      --no-tls --no-dtls --use-auth-secret --static-auth-secret=${TURN_SHARED_SECRET:-your-coturn-static-auth-secret}
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: voiddrop-caddy
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
